import React from "react";
import { FaDiscord, FaGithub, FaTwitch, FaTwitter } from "react-icons/fa";

const Footer = () => {
  const links = [
    {
      href: "https://discord.com",
      icon: <FaDiscord />,
    },
    {
      href: "https://x.com",
      icon: <FaTwitter />,
    },
    {
      href: "https://github.com",
      icon: <FaGithub />,
    },
    {
      href: "https://twitch.com",
      icon: <FaTwitch />,
    },
  ];
  return (
    <footer className="w-screen bg-violet-300 py-4 text-black">
      <div className="container mx-auto flex flex-col items-center justify-between gap-4 px-4 md:flex-row">
        <div>
          <p className="text-center text-sm font-light md:text-left">
            &copy; 2025 Nexia. All Rights Reserved.
          </p>
          <p className="text-center text-sm font-light md:text-left">
            All images and videos for this website are generated by Gemini AI via VEO 3 and Banana AI.
          </p>
        </div>

        <div className="flex justify-center gap-4 md:justify-start">
          {links.map((link) => (
            <a
              href={link.href}
              target="_blank"
              rel="noopener noreferrer"
              key={link.href}
              className="text-black transition-colors duration-500 ease-in-out hover:text-white"
            >
              {link.icon}
            </a>
          ))}
        </div>

        <a
          href="#privacy-policy"
          className="text-center text-sm hover:underline md:text-right"
        >
          Privacy Policy
        </a>
      </div>
    </footer>
  );
};

export default Footer;
